import Head from 'next/head';
import Layout from '@/components/Layout';
import * as Icons  from '@/components/icon';
import Image from 'next/image';
import Link from 'next/link';

import profilePic from "../../images/profile/blob.png";
import Animated  from '@/components/Animated';

export default function Home() {
  return (
    <>
      <Head>
        <title>Jean Daly | Artist</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
      <main className='flex items-center justify-between text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2'>
              <Image src={profilePic} alt="jean Daly" className='w-full h-auto' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <Animated  text="Turning Vision Into Reality With Code And Design." className=' !text-6xl text-left' />
              <p className='my-4 text-base font-extra'>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.</p>
              <div className="flex items-center self-start mt-2 space-x-4">
                <Link href="/" target={"_blank"}
                  className="flex items-center bg-indigo-500 text-dark p-2.5 px-6
                  rounded-lg text-lg font-semibold ring-2 ring-blue-500 ring-inset
                  hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  download={true}
                >Resume <Icons.DownloadIcon className={"w-6 ml-3"} />
                </Link>
                <Link href="/" target={"_blank"}
                  className="flex items-center bg-light text-dark p-2.5 px-6
                  rounded-lg text-lg font-semibold ring-2 ring-blue-500 ring-inset
                  hover:bg-indigo-500 hover:text-light border-2 border-solid border-transparent hover:border-dark"
                  
                >Projects <Icons.ProjectIcon  className={"w-6 ml-2"} />
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
